version: '3.1'

services: 

  postgres:
    container_name:  postgres
    image:           postgres
    restart: "on-failure"
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: .env
    networks:
      - app-tier

  redis:
    container_name:    redis
    image: redis
    restart: "on-failure"    
    ports:
      - 6379:6379
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
