# Generated by Django 4.0.2 on 2022-03-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('partnyorimg', models.FileField(upload_to='partimg/')),
            ],
        ),
    ]
