# Generated by Django 4.0.2 on 2022-03-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0002_partnyor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('productimg', models.FileField(upload_to='productimg/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldapp.product')),
            ],
        ),
    ]
