# Generated by Django 4.0.2 on 2022-03-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='partnyor',
            options={'verbose_name': 'Partnyor', 'verbose_name_plural': 'Partnyors'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterField(
            model_name='productslider',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
