# Generated by Django 4.0.2 on 2022-03-25 06:57

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0010_alter_images_options_alter_partnyor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Max 255 character', max_length=50, verbose_name='First Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('telephone', models.IntegerField()),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goldapp.category', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldapp.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='images',
            name='productimg',
            field=models.FileField(upload_to='productimg/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='partnyor',
            name='partnyorimg',
            field=models.FileField(upload_to='partimg/', verbose_name='Partnyor Image'),
        ),
        migrations.AlterField(
            model_name='partnyor',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldapp.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productimg',
            field=models.FileField(upload_to='productimg/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='productslider',
            name='prodslideimg',
            field=models.FileField(upload_to='slide/', verbose_name='Product Slide Image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slideimg',
            field=models.FileField(upload_to='slide/', verbose_name='Slide image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
