# Generated by Django 4.0.2 on 2022-03-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0011_contactus_alter_category_parent_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
