# Generated by Django 4.0.2 on 2022-03-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0012_alter_contactus_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_concrete',
            field=models.BooleanField(default=False, verbose_name='Concrete'),
        ),
    ]
