# Generated by Django 4.0.2 on 2022-05-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0014_newmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newmodel',
        ),
    ]
