# Generated by Django 4.0.2 on 2022-05-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0015_delete_newmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(help_text='Max 255 character', max_length=255, verbose_name='First Name'),
        ),
    ]
