# Generated by Django 4.0.2 on 2022-05-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0016_alter_contactus_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('newimg', models.FileField(upload_to='newimg/', verbose_name='New Image')),
            ],
        ),
    ]
