# Generated by Django 4.0.2 on 2022-05-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0018_delete_newmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_approximate',
            field=models.BooleanField(default=False, verbose_name='Approximate'),
        ),
    ]
