# Generated by Django 4.0.2 on 2022-05-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0020_alter_product_is_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aboutimg', models.FileField(upload_to='aboutimg/', verbose_name='About image')),
            ],
        ),
    ]
