# Generated by Django 4.0.2 on 2022-05-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0021_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
