# Generated by Django 4.0.2 on 2022-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0022_delete_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('is_mainpage', models.BooleanField(default=False, verbose_name='Main page')),
            ],
        ),
    ]
