# Generated by Django 4.0.2 on 2022-05-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0027_remove_product_name_az_remove_product_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
