# Generated by Django 4.0.2 on 2022-06-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapp', '0029_category_title_az_category_title_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('engslideimg', models.FileField(upload_to='slide/', verbose_name='English slide image')),
            ],
            options={
                'verbose_name': 'English Slider',
                'verbose_name_plural': 'English Sliders',
            },
        ),
    ]
